### PR TITLE
Fix: Subcommands can no longer be written twice

### LINKED ISSUE #27: Subcommands can be written twice during invocation
## Summary

A clear and concise summary of the bug.

## Steps To Reproduce The Bug

Using this `cli.ts`

```typescript
import * as Line from "https://deno.land/x/line@v1.0.0/mod.ts";

class MainCommand extends Line.MainCommand {
    public signature = "main";
    public description = "The main command.";

    public subcommands = [
      Subcommand,
    ];

    public handle(): void {
        console.log("Main command.");
    }
}

class Subcommand extends Line.Subcommand {
    public signature = "sub";
    public description = "A subcommand.";

    public handle() {
        console.log("The subcommand.");
    }
}

// Construct your Line.CLI object and plug in your main command

const cli = new Line.CLI({
    name: "A main command with a subcommand.", // Required config
    description: "To reproduce subcommands being written twice.", // Required config
    version: "v1.0.0", // Required config
    command: MainCommand, // Required config
});

// Run your CLI

cli.run();
```

1. `deno run cli.ts` - prints help :heavy_check_mark: 
2. `deno run cli.ts sub` - prints "A subcommand." :heavy_check_mark: 
3. `deno run cli.ts sub foo` - prints "[ERROR] Subcommand 'sub' used incorrectly." :heavy_check_mark: 
4. `deno run cli.ts sub sub` - prints "A subcommand." :warning: :thinking: 

## Expected Behavior

I would have expected a subcommand name can be written only once, and writing `sub sub` would result in "[ERROR] Subcommand 'sub' used incorrectly." 

## Suggested Solution(s)

Unsure, I haven't looked at the code.

## Screenshots

[asciicast](https://asciinema.org/a/nZqgSwOqolzaGlEHBm31aRT5A)

## Additional Context

none

### PR DESCRIPTION
**Pull request by dXu23**
Fixes #27 

## Summary

Two lines of code seemed to be unnecessary, considering that all tests pass without them

It might be worth adding an extra test similar to what is described in the issue to make sure it doesn't happen again.

### CODE REVIEW

**Comment by ebebbington** [comment]
@dXu23 thanks :) I don’t suppose you could write a test case for this?

**Comment by dXu23** [comment]
I'm not too sure this is actually a bug now that I think about it. 
[My comment on the issue](https://github.com/drashland/line/issues/27#issuecomment-1059355079)

**Comment by ebebbington** [comment]
@dXu23 The issue isn’t being able to do `read read`, the issue is that if a user does that, it’s acting as if the last “read” is a subcommands, when it should be acting as an argument to a subcommand

**Comment by dXu23** [comment]
My [bad](https://github.com/drashland/line/issues/27#issuecomment-1059412644), nvm.

**Comment by crookse** [comment]
hey @dXu23 , i made a pull request to your work: https://github.com/dXu23/line-1/pull/1

please review. thanks!

**Review by dXu23 — COMMENTED** [review]
Looks good to me.

**Review by crookse — APPROVED** [review]

**Comment by crookse** [comment]
@dXu23 👍🏻

**Pull request merged**
